# theme
colorscheme dracula-transparent

# Disable clippy
set global ui_options ncurses_assistant=dilbert

# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Display line numbers
add-highlighter global/ number-lines -hlcursor

# Show whitespaces
add-highlighter global/ show-whitespaces

# Indent to 80 columns
add-highlighter global/ wrap -word -indent -width 80
